gifubus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('time_search.urls')),
]

time_search/urls.py
from django.urls import path

from . import views

app_name = 'time_search'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('result/', views.SearchResultView.as_view(), name='result'),
    path('guideline/', views.GuideLineView.as_view(), name='guideline'),
    path('analysis/', views.AnalysisView.as_view(), name='analysis'),
]

time_search/models.py
from django.db import models

class Guide(models.Model):
    collect_time = models.DateTimeField()
    departure_place = models.CharField(max_length=100)
    departure_time = models.DateTimeField()
    arrival_place = models.CharField(max_length=100)
    #line_name = models.CharField(max_length=100)
    line_id = models.CharField(max_length=100)
    destination = models.CharField(max_length=100)
    delay_time = models.IntegerField()

    def __str__(self):
        #return str(self.collect_time)
        return '{0}---{1}'.format(self.collect_time, self.departure_time)

time_search/views.py
import datetime
import pytz

from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils.timezone import make_aware

from .models import Guide
from .scraping import *


BUS_STOPS = ['名鉄岐阜（神田町通り）',
             'ＪＲ岐阜',
             'メディアコスモス・鶯谷高校口',
             '岐阜大学',
             '岐阜大学病院']


"""
METHOD
"""
def get_delayed_time(dep_t, delay_t):
    dep_t = dep_t.strftime('%Y-%m-%d %H:%M:00')
    dep_t = datetime.datetime.strptime(dep_t, '%Y-%m-%d %H:%M:%S')
    dep_t = dep_t + datetime.timedelta(hours=9)
    delay_t = dep_t + datetime.timedelta(minutes=delay_t)

    return dep_t.strftime('%H:%M'), delay_t.strftime('%H:%M')


"""
class
"""

class IndexView(generic.TemplateView):
    template_name = 'time_search/index.html'

    def get_context_data(self, **kargs):
        context = super().get_context_data(**kargs)

        context['bus_stops'] = BUS_STOPS

        return context

class GuideLineView(generic.TemplateView):
    template_name = 'time_search/guideline.html'

class AnalysisView(generic.TemplateView):
    template_name = 'time_search/analysis.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['xlabels'] = [i for i in range(5, 25)]
        context['label'] = '毎時間ごとの遅延時間の平均'
        context['data'] = [i for i in range(20)]

        return context

class SearchResultView(generic.ListView):
    model = Guide
    paginate_by = 10
    #context_object_name = 'guides'
    template_name = 'time_search/search_result.html'

    def get_context_data(self, **kwargs):

        is_debug = False

        context = super().get_context_data(**kwargs)
        data = []
        now = datetime.datetime.now()

        dep_stop_name = self.request.GET['dep_stop_name']
        arr_stop_name = self.request.GET['arr_stop_name']

        if not is_debug:

            url = get_url(now.hour, now.minute, dep_stop_name, arr_stop_name)
            print(url)
            df = get_data(url)
            d = df.T.to_dict()

            for _d in d.values():
                collect_time = datetime.datetime.strptime(_d['collect_time'], '%Y-%m-%d %H:%M:%S')
                collect_time = make_aware(collect_time)

                departure_time = collect_time.strftime('%Y-%m-%d {0}:{1}:00'.format(*_d['発時刻'].split(':')))
                departure_time = datetime.datetime.strptime(departure_time, '%Y-%m-%d %H:%M:%S')
                departure_time = make_aware(departure_time)

                print('collect_time: ', collect_time, collect_time.tzinfo)
                print('departure_time: ', departure_time, departure_time.tzinfo)

                g = Guide(collect_time=collect_time,
                          departure_place=_d['departure_place'],
                          departure_time=departure_time,
                          arrival_place=_d['arrival_place'],
                          line_id=_d['行先番号'],
                          destination=_d['行き先'],
                          delay_time=_d['delay_time'])

                g.save()

            guides = Guide.objects.filter(departure_time__date=datetime.date(now.year, now.month, now.day),
                                          departure_time__time__range=(datetime.time(now.hour, now.minute), datetime.time(23, 59)),
                                          departure_place=dep_stop_name, arrival_place=arr_stop_name,
                                          collect_time=collect_time
                                          ).distinct()
        else:
            guides = Guide.objects.filter(departure_place=dep_stop_name, arrival_place=arr_stop_name)

        for g in guides:
            dep_t, dep_delay_t = get_delayed_time(g.departure_time, g.delay_time)
            dic = {'dep_t': dep_t, 'dep_delay_t': dep_delay_t,
                   'delay_t': g.delay_time,
                   'line_id': g.line_id,
                   'destination': g.destination}
            data.append(dic)

        data = sorted(data, key=lambda d: d['dep_delay_t'])

        keys = []
        _data = []
        for d in data:
            s = d['dep_t'] + d['line_id']
            keys.append(s)
            l = len(keys)
            keys = list(set(keys))
            if len(keys) == l:
                _data.append(d)


        context['guides'] = _data

        context['now'] = now.strftime('%Y/%m/%d %H:%M:%S')

        context['dep_stop_name'] = dep_stop_name
        context['arr_stop_name'] = arr_stop_name

        try:
            context['collect_time'] = guides[0].collect_time
        except:
            context['collect_time'] = collect_time

        return context

time_search/templates/time_search/analysis.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>ANALYSIS</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

  </head>
  <body>

    {% block navigation-bar %}
      {% include 'time_search/navigation_bar.html' %}
    {% endblock %}

    <br>

    <div class="textarea-white">

      <div align="center">
        <p class="sub-title">遅延の分析</p>
      </div>

      <div id="chart-area"></div>

    </div>

    <script type="text/javascript" src="{% static 'js/Chart.bundle.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/analysis.js' %}"></script>
    <script type="text/javascript">
      loadCharts({{ xlabels }}, "{{ label }}", {{ data }}, "dep_stop_name", "arr_stop_name");
      loadCharts({{ xlabels }}, "{{ label }}", {{ data }}, "dep_stop_name", "arr_stop_name");
      loadCharts({{ xlabels }}, "{{ label }}", {{ data }}, "dep_stop_name", "arr_stop_name");
    </script>

  </body>
</html>

time_search/templates/time_search/guideline.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">

  <head>
    <meta charset="utf-8">
    <title>GUIDELINE</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

  </head>
  <body>

    {% block navigation-bar %}
      {% include 'time_search/navigation_bar.html' %}
    {% endblock %}

    <div class="top-image cb">
      <img src="{% static 'time_search/bus2.jpg' %}">
      <p>岐阜バスをもっと快適に</p>
    </div>

    <br><br><br>

    <div class="textarea-white position-center">

      <br>

      <h1>GifuBusUI とは</h1>

      <div class="position-center usage">
        <p class="usage">GifuBusUI はいつも使うバス停の時刻検索をより簡単にし、遅延情報も考慮した時刻表示をしてくれるWebアプリです。</p>
        <p class="usage">さらに、遅延のデータを収集し分析することで、バス停ごとにどれくらい遅延するかの予測を行うことができます。</p>
      </div>

      <h1>使い方</h1>

      <table class="usage">
        <tr>
          <td>
            <div class="usage">
              <h2>バス停の選択はボタン操作だけ</h2>
              <p>いつも使うバス停なので、毎回テキストで入力するのは面倒。</p>
              <p>よく使うバス停をボタンで用意しているので、タッチするだけでバス停を選択できます。</p>
            </div>
          </td>
          <td class="concept-image">
            <img src="{% static 'time_search/demo_search.png' %}">
          </td>
        </tr>
      </table>

      <table class="usage">
        <tr>
          <td class="concept-image">
            <img src="{% static 'time_search/demo_search_result.png' %}">
          </td>
          <td>
            <div class="usage">
              <h2>遅延で並び替えた時刻表</h2>
              <p>バスは予想以上によく遅延が発生します。</p>
              <p>バス停ごとに遅延情報を取得し、遅延した出発時間で並び替えた時刻表を提供します。</p>
            </div>
          </td>
        </tr>
      </table>

      <table class="usage">
        <tr>
          <td>
            <div class="usage">
              <h2>遅延情報の分析</h2>
              <p>バス停ごとに、遅延のしやすさは大きく異なります。</p>
              <p>バス停ごとの遅延情報を大量に使用して、遅延の分析・予測を行います。</p>
            </div>
          </td>
          <td class="concept-image">
            <img src="{% static 'time_search/.png' %}">
          </td>
        </tr>
      </table>

      <br>

    </div>

    <br><br>



  </body>
</html>

time_search/templates/time_search/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">



  <head>
    <meta charset="utf-8">
    <title>SEARCH</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script type="text/javascript" src="{% static 'js/index.js' %}"></script>

  </head>

  <body>

    {% block navigation-bar %}
      {% include 'time_search/navigation_bar.html' %}
    {% endblock %}

    <br>

    <div class="textarea-white">

      <div align="center">
        <p class="sub-title">時刻検索</p>
      </div>

      <form action="{% url 'time_search:result' %}" method="get" onsubmit="return check();">
        {% csrf_token %}

        <div class="dep-stop selected-stop-header">
          <p>出発地</p>
        </div>

        <div class="arr-stop selected-stop-header">
          <p>到着地</p>
        </div>

        <br class="cb">

        <div class="dep-stop selected-stop">
          <p id="dep_stop">出発地のバス停名</p>
          <input class="selected-dep-stop" name="dep_stop_name" type="hidden" value="出発地のバス停名">
        </div>

        <div class="arr-stop selected-stop">
          <p id="arr_stop">到着地のバス停名</p>
          <input class="selected-arr-stop" name="arr_stop_name" type="hidden" value="到着地のバス停名">
        </div>

        <br class="cb">

        <br>

        <div class="bus-img">
          <img src="{% static 'time_search/bus_red_white.png' %}">
        </div>

        <br>
        <!--
        <p class="btn-search" type="submit">検索</p>
        -->
        <div align="center">
          <input class="btn-search" type="submit" name="" value="検索">
        </div>

        <br><br>

        <div class="dep-stop">
          {% for s in bus_stops %}
            <p class="dep_stop_btn btn-flat-simple">{{ s }}</p>
            <br>
          {% endfor %}
        </div>

        <div class="arr-stop">
          {% for s in bus_stops %}
            <p class="arr_stop_btn btn-flat-simple">{{ s }}</p>
            <br>
          {% endfor %}
        </div>

        <br class="cb">

      </form>

      <br><br>

    </div>

    <br><br>

  </body>



</html>

time_search/templates/time_search/navigation_bar.html
{% block navigation-bar %}
  <p class="app-title float-left">GifuBusUI</p>

  <div class="text-white">
    <p class="float-right">
      <a class="nav-bar" href="{% url 'time_search:analysis' %}">ANALYSIS</a>
    </p>
    <p class="float-right">
      <a class="nav-bar" href="{% url 'time_search:index' %}">SEARCH</a>
    </p>
    <p class="float-right">
      <a class="nav-bar" href="{% url 'time_search:guideline' %}">GUIDELINE</a>
    </p>
  </div>

  <hr class="cb">
{% endblock %}

time_search/templates/time_search/search_result.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">


  <head>
    <meta charset="utf-8">
    <title>SEARCH RESULT PAGE</title>

    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

  </head>


  <body>

    {% block navigation-bar %}
      {% include 'time_search/navigation_bar.html' %}
    {% endblock %}

    <br>

    <div class="textarea-white">

      <div align="center">
        <p class="sub-title">接近情報</p>
      </div>

      <div class="dep-stop selected-stop-header">
        <p>出発地</p>
      </div>

      <div class="arr-stop selected-stop-header">
        <p>到着地</p>
      </div>

      <br class="cb">

      <div class="dep-stop selected-stop">
        <p id="dep_stop">{{ dep_stop_name }}</p>
      </div>

      <div class="arr-stop selected-stop">
        <p id="arr_stop">{{ arr_stop_name }}</p>
      </div>

      <br class="cb">

      <br>

      <div align="center">
        <p>{{ collect_time }} 現在</p>
        <form action="{% url 'time_search:result' %}" method="get">
          <input type="hidden" name="dep_stop_name" value="{{ dep_stop_name }}">
          <input type="hidden" name="arr_stop_name" value="{{ arr_stop_name }}">
          <a href="{% url 'time_search:result' %}"><input class="btn-update" type="submit" name="" value="UPDATE"></a>
        </form>
      </div>

      <br><br>

      {% for g in guides %}

        {% if not g.delay_t == 0 %}

          <table class="delayed-frame">
            <tr>
              <td>{{ g.line_id }}</td>
              <td class="delayed-normal bus-time">{{ g.dep_t }} <i class="fa fa-caret-right"></i> {{ g.arr_delay_t }}</td>
              <td rowspan="2">
                <p class="delayed"> <i class="fa fa-clock"></i> &nbsp; {{ g.delay_t }}分遅延</p>
              </td>
            </tr>
            <tr>
              <td class="delayed_box">遅延あり</td>
              <td class="delayed bus-time">{{ g.dep_delay_t}} <i class="fa fa-caret-right"></i> {{ g.arr_delay_t }}</td>
            </tr>
          </table>

        {% else %}

          <table class="normal-frame">
            <tr>
              <td>{{ g.line_id }}</td>
              <td class="bus-time">{{ g.dep_t }} <i class="fa fa-caret-right"></i> {{ g.arr_delay_t }}</td>
              <td rowspan="2">
                <p> <i class="fa fa-clock"></i> &nbsp; 通常運行 </p>
              </td>
            </tr>
            <tr>
              <td class="normal_box">遅延なし</td>
              <td class="bus-time"> --- </td>
            </tr>
          </table>

        {% endif %}

        <br>

      {% endfor %}

    </div>

    <br><br>


  </body>


</html>